# Makefile for 0019_1_classes
Cat: 0019_1_Cat.o 0019_1_classes.o
	g++ 0019_1_Cat.o 0019_1_classes.o -o Cat

0019_1_Cat.o: 0019_1_Cat.cpp
	g++ -c 0019_1_Cat.cpp

0019_1_classes.o: 0019_1_classes.cpp
	g++ -c 0019_1_classes.cpp

clean:
	rm *.o *.exe