# Makefile for 17_test
game.exe: main.cpp Creature.cpp Player.cpp Monster.cpp Random.cpp Action.cpp
	g++ main.cpp Creature.cpp Player.cpp Monster.cpp Random.cpp Action.cpp -o game.exe

# Creature.o: Creature.cpp
# 	g++ -c Creature.cpp

# Player.o: Player.cpp
# 	g++ -c Player.cpp

# Monster.o: Monster.cpp
# 	g++ -c Monster.cpp

# main.o: main.cpp
# 	g++ -c main.cpp

clean:
	rm *.o *.exe